// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js'

const SUPABASE_URL = "https://pdifcfsndjmblxugqzdm.supabase.co"
const SUPABASE_SERVICE_ROLE_KEY = "sb_secret_OlgX53a3H-iASR6BnfpO8A_QS8pL01a"

// Service role client — bypasses RLS, use server-side only
export const supabaseAdmin = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
  auth: {
    autoRefreshToken: false,
    persistSession: false,
  },
})