// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://pdifcfsndjmblxugqzdm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBkaWZjZnNuZGptYmx4dWd6ZG0iLCJyb2xlIjoiYW5vbiIsImlhdCI6MTc1MTk2NTg1MywiZXhwIjoyMDY3NTQxODUzfQ.ZUD6gZNbO3UcJcqUXmWrT_a9jqD0pVgVLcX4gXNJQ_c";

// Browser/client-side Supabase client (uses publishable key)
export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Server-side Supabase admin client (uses service role key from env)
const SUPABASE_SERVICE_ROLE_KEY = import.meta.env.SUPABASE_SERVICE_ROLE_KEY || "";
export const supabaseAdmin = SUPABASE_SERVICE_ROLE_KEY
  ? createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, { auth: { persistSession: false } })
  : null;
